# Generated by Django 3.1.1 on 2020-09-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slackpost',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='slackpost',
            name='user',
        ),
    ]
