# Generated by Django 3.1.1 on 2020-09-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20200907_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('resource', models.URLField()),
            ],
        ),
    ]
