# Generated by Django 3.1.1 on 2020-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_answersdatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('aliases', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='answersdatabase',
            name='context',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answersdatabase',
            name='resource',
            field=models.TextField(),
        ),
    ]
